// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  tick: __t.u64(),
  timestamp: __t.string(),
  playerX: __t.u32(),
  playerZ: __t.u32(),
  playerHp: __t.u32(),
  playerMaxHp: __t.u32(),
  combatLevel: __t.u32(),
  inCombat: __t.bool(),
  toonState: __t.string(),
};
