// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  fromName: __t.string().name("from_name"),
  fromX: __t.u32().name("from_x"),
  fromZ: __t.u32().name("from_z"),
  toName: __t.string().name("to_name"),
  toX: __t.u32().name("to_x"),
  toZ: __t.u32().name("to_z"),
  safety: __t.f32(),
  dangers: __t.string(),
  waypoints: __t.string(),
  lastUsed: __t.string().name("last_used"),
  timesUsed: __t.u32().name("times_used"),
});
