// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  tick: __t.u64(),
  timestamp: __t.string(),
  playerX: __t.u32().name("player_x"),
  playerZ: __t.u32().name("player_z"),
  playerHp: __t.u32().name("player_hp"),
  playerMaxHp: __t.u32().name("player_max_hp"),
  combatLevel: __t.u32().name("combat_level"),
  inCombat: __t.bool().name("in_combat"),
  toonState: __t.string().name("toon_state"),
});
