// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActionLog = __t.object("ActionLog", {
  id: __t.u64(),
  tick: __t.u64(),
  timestamp: __t.string(),
  agent: __t.string(),
  actionType: __t.string(),
  target: __t.string(),
  result: __t.string(),
  context: __t.string(),
});
export type ActionLog = __Infer<typeof ActionLog>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.u64(),
  tick: __t.u64(),
  timestamp: __t.string(),
  eventType: __t.string(),
  data: __t.string(),
  agent: __t.string(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const Knowledge = __t.object("Knowledge", {
  id: __t.string(),
  category: __t.string(),
  title: __t.string(),
  content: __t.string(),
  confidence: __t.f32(),
  lastVerified: __t.string(),
  timesUsed: __t.u32(),
});
export type Knowledge = __Infer<typeof Knowledge>;

export const Observation = __t.object("Observation", {
  id: __t.u64(),
  timestamp: __t.string(),
  whatHappened: __t.string(),
  whyInferred: __t.string(),
  context: __t.string(),
  lesson: __t.string(),
});
export type Observation = __Infer<typeof Observation>;

export const Route = __t.object("Route", {
  id: __t.string(),
  fromName: __t.string(),
  fromX: __t.u32(),
  fromZ: __t.u32(),
  toName: __t.string(),
  toX: __t.u32(),
  toZ: __t.u32(),
  safety: __t.f32(),
  dangers: __t.string(),
  waypoints: __t.string(),
  lastUsed: __t.string(),
  timesUsed: __t.u32(),
});
export type Route = __Infer<typeof Route>;

export const StateSnapshot = __t.object("StateSnapshot", {
  id: __t.u64(),
  tick: __t.u64(),
  timestamp: __t.string(),
  playerX: __t.u32(),
  playerZ: __t.u32(),
  playerHp: __t.u32(),
  playerMaxHp: __t.u32(),
  combatLevel: __t.u32(),
  inCombat: __t.bool(),
  toonState: __t.string(),
});
export type StateSnapshot = __Infer<typeof StateSnapshot>;

