// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  fromName: __t.string(),
  fromX: __t.u32(),
  fromZ: __t.u32(),
  toName: __t.string(),
  toX: __t.u32(),
  toZ: __t.u32(),
  safety: __t.f32(),
  dangers: __t.string(),
  waypoints: __t.string(),
};
