// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import LogActionReducer from "../log_action_reducer";
import LogEventReducer from "../log_event_reducer";
import LogObservationReducer from "../log_observation_reducer";
import LogStateReducer from "../log_state_reducer";
import UpsertKnowledgeReducer from "../upsert_knowledge_reducer";
import UpsertRouteReducer from "../upsert_route_reducer";

export type LogActionParams = __Infer<typeof LogActionReducer>;
export type LogEventParams = __Infer<typeof LogEventReducer>;
export type LogObservationParams = __Infer<typeof LogObservationReducer>;
export type LogStateParams = __Infer<typeof LogStateReducer>;
export type UpsertKnowledgeParams = __Infer<typeof UpsertKnowledgeReducer>;
export type UpsertRouteParams = __Infer<typeof UpsertRouteReducer>;

